(ns mino-site.content.get-started
  "Get Started page content."
  (:require
    [hiccup2.core :as h]))

(defn get-started-page
  "Generates the Get Started page HTML body."
  []
  (str
    (h/html
      [:h1 "Get Started"]

      [:p "Two paths. If you only want to try the language and run "
       "the REPL, install the standalone binary. If you are embedding "
       "mino in a host program, build from source so you have the "
       "headers and per-subsystem object files on hand."]

      [:h2 "1. Install the standalone REPL"]
      [:p "Pre-built binaries ship through Homebrew (macOS, Linux) "
       "and Scoop (Windows). Both bundle the standard library and "
       "drop a single " [:code "mino"] " executable on " [:code "PATH"] "."]

      [:h3 "Homebrew"]
      [:pre [:code "brew install leifericf/mino/mino"]]
      [:p "On first install brew taps "
       [:a {:href "https://github.com/leifericf/homebrew-mino"}
        "leifericf/homebrew-mino"] " automatically. "
       [:code "brew upgrade mino"] " picks up new releases."]

      [:h3 "Scoop"]
      [:pre [:code "scoop bucket add mino https://github.com/leifericf/scoop-mino\nscoop install mino"]]
      [:p [:code "scoop update mino"] " picks up new releases."]

      [:h3 "Direct download (Linux, static)"]
      [:p "Each release also publishes a fully static Linux binary "
       "(amd64 and arm64), built against musl. It is a single file with "
       "no dynamic dependencies "
       [:span {:title "zero ELF NEEDED entries"} "(zero shared-library "
        "links)"] ", so it runs on any Linux — glibc or musl, Alpine, "
       "old kernels or new — with nothing to install. Grab "
       [:code "mino_linux_<arch>_musl_<version>.tar.gz"] " from the "
       [:a {:href "https://github.com/leifericf/mino/releases"}
        "releases page"] ", unpack, and run:"]
      [:pre [:code "tar -xzf mino_linux_amd64_musl_*.tar.gz\n./mino_linux_amd64_musl_*/mino --version"]]
      [:p "These are cross-compiled from one host with a pinned "
       [:code "zig cc"] "; the glibc-dynamic builds remain available as "
       "the platform-native artifacts."]

      [:h3 "Verify"]
      [:pre [:code "mino --version\nmino"]]
      [:p "The first command prints the installed version. The "
       "second drops you into the REPL."]

      [:h2 "2. Get the source"]
      [:p "For embedding, contributing, or running on a platform "
       "that brew and scoop don't cover, clone the repository:"]
      [:pre [:code "git clone https://github.com/leifericf/mino.git"]]
      [:p "Or "
       [:a {:href "https://github.com/leifericf/mino/archive/refs/heads/main.zip"}
        "download a zip archive"]
       ". mino is a small C99 codebase in " [:code "src/"]
       ". Any C99 compiler, no external dependencies."]

      [:h2 "3. Build"]
      [:p "The C tree is split into per-subsystem subdirectories "
       "under " [:code "src/"] ". Bootstrap with "
       [:code "make"] ":"]
      [:pre
       [:code
"cd mino
make
./mino"]]
      [:p [:code "make"] " is the bootstrap step only — it generates "
       "the bundled-source headers and compiles the binary from a "
       "clean checkout. Every other build, test, and tooling task "
       "runs through the binary itself: "
       [:code "./mino task build"] " for incremental rebuilds, "
       [:code "./mino task test"] " for the test suite, "
       [:code "./mino task build-asan"] " for an ASan-instrumented "
       "build, " [:code "./mino task"] " on its own to list what's "
       "available."]
      [:p "Or compile mino directly into your own program. mino "
       "ships a single-file amalgamation — one " [:code ".c"] " and "
       "one " [:code ".h"] " — generated by:"]
      [:pre [:code "./mino task amalgamate"]]
      [:p "Drop the resulting " [:code "dist/mino.c"] " and "
       [:code "dist/mino.h"] " into your project tree and compile "
       "alongside your own sources:"]
      [:pre
       [:code "cc -std=c99 -O2 -o myapp myapp.c dist/mino.c -lm -lpthread"]]
      [:p "One include, one " [:code ".c"] " file, no per-subsystem "
       [:code "-I"] " flags. The amalgamation is the canonical "
       "drop-in shape for embedders integrating mino into a host "
       "project tree."]
      [:p "Run the test suite:"]
      [:pre [:code "./mino task test"]]

      [:h2 "4. Embed in your C program"]
      [:p "A minimal embedding creates a runtime, registers a host "
       "function, evaluates mino code, and extracts the result:"]
      [:pre
       [:code {:data-lang "c"}
"#include \"mino.h\"
#include <stdio.h>

/* A host function exposed to mino as (add-tax amount). */
static mino_val *host_add_tax(mino_state *S, mino_val *args,
                                mino_env *env)
{
    long long amount;
    (void)env;
    if (!mino_is_cons(args) || !mino_to_int(mino_car(args), &amount))
        return mino_nil(S);
    return mino_float(S, (double)amount * 1.08);
}

int main(void)
{
    mino_state *S   = mino_state_new();
    mino_env   *env = mino_env_new(S);
    mino_install(S, env, MINO_CAP_DEFAULT);  /* sandbox preset      */
    mino_register_fn(S, env, \"add-tax\", host_add_tax);

    mino_val *result = mino_eval_string(S,
        \"(def prices [100 200 300])\\n\"
        \"(reduce + (map add-tax prices))\\n\",
        env);

    if (result) {
        double total;
        if (mino_to_float(result, &total))
            printf(\"total with tax: %.2f\\n\", total);
    }

    mino_env_free(S, env);
    mino_state_free(S);
    return 0;
}"]]
      [:p "Key points:"]
      [:ul
       [:li [:code "mino_state_new()"] " creates an isolated runtime "
        "state that owns the GC, intern tables, and all allocated "
        "objects."]
       [:li [:code "mino_env_new(S)"] " creates an empty environment; "
        [:code "mino_install(S, env, MINO_CAP_DEFAULT)"]
        " loads the sandbox preset (core + safe stdlib, no I/O)."]
       [:li [:code "mino_register_fn()"] " exposes a C function to "
        "mino code under any name."]
       [:li [:code "mino_eval_string()"] " reads and evaluates all "
        "forms, returning the last result."]
       [:li [:code "mino_to_float()"] " safely extracts a C value "
        "from the result (returns 0 on type mismatch)."]
       [:li [:code "mino_env_free()"] " and "
        [:code "mino_state_free()"] " tear down the environment "
        "and state."]]

      [:h2 "5. Try the REPL"]
      [:p "The standalone REPL is useful for exploring the language "
       "interactively:"]
       [:pre
        [:code {:data-lang "mino"}
"$ mino
mino 2026.08.08-alpha1
Type :help for help, :quit to exit
mino=> (def greet (fn [name] (str \"hello, \" name \"!\")))
#'user/greet
mino=> (greet \"world\")
\"hello, world!\"
mino=> (map greet [\"alice\" \"bob\" \"carol\"])
(\"hello, alice!\" \"hello, bob!\" \"hello, carol!\")
mino=> (doc map)
Returns a lazy sequence of applying f to each item in coll. When
   called with multiple collections, maps f across them in parallel.
   When called with no collection, returns a transducer.
nil"]]

      [:h2 "Next steps"]
      [:ul
       [:li [:a {:href "/documentation/embedding/"} "Embedding Guide"]
        ": state lifecycle, value ownership, sandboxing, handles, "
        "and threading rules."]
       [:li [:a {:href "/documentation/api/"} "C API Reference"]
        ": every public function, type, and enum."]
       [:li [:a {:href "/documentation/language/"} "Language Reference"]
        ": every built-in function, special form, and macro."]
       [:li [:a {:href "/documentation/cookbook/"} "Embedding Cookbook"]
        ": twelve worked examples for real-world patterns."]]

      [:h2 "License"]
      [:p "mino is released under the "
       [:a {:href "https://opensource.org/licenses/MIT"} "MIT License"]
       ". Use it for anything."])))
